### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sishenyihuba** [blueapron/Mandoline#4]
I check the Podfile that this example is using the dynamic framework Mandoline,But there is an compile error:   could not read data from '/Users/macache/Downloads/WorkPlace/UI Stuff/Mandoline-master/Example/Pods/Target Support Files/Mandoline/ResourceBundle-Mandoline-Info.plist': The file “ResourceBundle-Mandoline-Info.plist” couldn’t be opened because there is no such file.

And can not find Mandoline framework.
<img width="719" alt="jietu20171102-084004" src="https://user-images.githubusercontent.com/7836659/32304338-7a54bef2-bfa9-11e7-90ce-2f608d52b82c.png">

**Comment by anatg** [comment]
Hi there,
Thanks for checking out the pod! Did this happen after `pod install`-ing on the example project or within your own project? I haven't shared the schemes to make this a dynamic framework yet, so that might be an issue I don't want to rule out. If you have any other details you can share about the steps you took, I can see if I can recreate this.

Thanks for your patience!

**Comment by NewKoder4418** [comment]
Hi,

I also faced the same problem. 

To solve this I ran the command 

**pod install**

and then command line prompted me to update the repo , so I ran the following command 

**pod repo update** 

and after that I again I ran this command 

**pod install**

HTH...

**Comment by anatg** [comment]
@B4V4-G, good call! @sishenyihuba, I just pushed an update to the repo. I think after checking out `master` you should be all set. Please let me know if you have any other issues!

**Comment by sishenyihuba** [comment]
Thanks so much ,I will try tonight
